spring.application.name=patient-service
server.port=8082


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver






# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=patient-service

# MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/patientdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



# Keycloak JWT validation
keycloak.auth-server-url=http://keycloak:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/alzheimer-realm/protocol/openid-connect/certs

# User Service URL
user.service.url=http://user-service:8084

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

